// Auth
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_CLEAR_MESSAGE = "AUTH_CLEAR_MESSAGE";

// Laptop
export const LAPTOP_LOADING = "LAPTOP_LOADING";
export const LAPTOP_ERROR = "LAPTOP_ERROR";
export const LAPTOP_FETCH = "LAPTOP_FETCH";
export const LAPTOP_FETCH_ONE = "LAPTOP_FETCH_ONE";

// Cart
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_BUY_SUCCESS = "CART_BUY_SUCCESS";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_ERROR = "CART_ERROR";
export const CART_LOADING = "CART_LOADING";
export const CART_CLEAR_MESSAGE = "CART_CLEAR_MESSAGE";
