// Auth
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_CLEAR_MESSAGE = "AUTH_CLEAR_MESSAGE";

// Laptop
export const LAPTOP_LOADING = "LAPTOP_LOADING";
export const LAPTOP_MESSAGE = "LAPTOP_MESSAGE";
export const LAPTOP_CLEAR_MESSAGE = "LAPTOP_CLEAR_MESSAGE";
export const LAPTOP_FETCH = "LAPTOP_FETCH";
export const LAPTOP_FETCH_ONE = "LAPTOP_FETCH_ONE";
export const LAPTOP_CHANGE_SKIP = "LAPTOP_CHANGE_SKIP";
export const LAPTOP_CHANGE_SORT = "LAPTOP_CHANGE_SORT";
export const LAPTOP_CHANGE_GRID_SIZE = "LAPTOP_CHANGE_GRID_SIZE";

// Cart
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_BUY_SUCCESS = "CART_BUY_SUCCESS";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_ERROR = "CART_ERROR";
export const CART_LOADING = "CART_LOADING";
export const CART_CLEAR_MESSAGE = "CART_CLEAR_MESSAGE";

// Filter
export const FILTER_APPLY = "FILTER_APPLY";
export const FILTER_TOGGLE_BRAND = "FILTER_TOGGLE_BRAND";
export const FILTER_TOGGLE_CORE = "FILTER_TOGGLE_CORE";
export const FILTER_TOGGLE_RAM = "FILTER_TOGGLE_RAM";
export const FILTER_RESET = "FILTER_RESET";

// User
export const CHANGE_DARKMODE = "CHANGE_DARKMODE";
export const UPDATE_PURCHASES = "UPDATE_PURCHASES";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_MAILING = "UPDATE_MAILING";
export const UPDATE_INFO = "UPDATE_INFO";
export const USER_CLEAR_MESSAGE = "USER_CLEAR_MESSAGE";
export const USER_ERROR = "USER_ERROR";
export const USER_LOADING = "USER_LOADING";
